[package]
name = "ssnt"
version = "0.1.0"
authors = ["Alain Siegrist <alainsiegrist02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5", features = ["dynamic"] }
bevy_fly_camera = { git = "https://github.com/aloucks/bevy_fly_camera", branch = "bevy_main" }
nom = "6.1.2"
cfg-if = "1.0.0"
anyhow = "1.0.40"
futures-lite = "1.4.0"

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }