[package]
name = "ssnt"
version = "0.1.0"
authors = ["Alain Siegrist <alainsiegrist02@gmail.com>"]
edition = "2021"

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
bevy = "0.9"
bevy_rapier3d = "0.19.0"


[dependencies]
byond = { path = "crates/byond" }
maps = { path = "crates/maps" }
networking = { path = "crates/networking" }
bevy = { workspace = true, features = ["bevy_gltf"] }
bevy_egui = "0.17.1"
bevy-inspector-egui = "0.14.0"
bevy_rapier3d = { workspace = true, features = ["simd-stable"] }
bevy_common_assets = { version = "0.4.0", features = ["ron"] }
cfg-if = "1.0.0"
futures-lite = "1.4.0"
log = "0.4.8"
glam = "0.20.2"
serde = { version = "*", features = ["derive"] }
clap = { version = "3.0.13", features = ["derive"] }
toml = "0.5.9"
reqwest =  { version = "0.11.12", features = ["json"] }
async-compat = "0.2.1"
tokio = { version = "1.21.2", features = ["time"] }
# Remove when https://github.com/bevyengine/bevy/pull/6578 is merged
smallvec = "*"

[patch.crates-io]
bevy = { git = "https://github.com/Alainx277/bevy", branch = "ssnt" }
bevy_ecs = { git = "https://github.com/Alainx277/bevy", branch = "ssnt" }
# bevy = { path = "../bevy" }

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.maps]
opt-level = 1

[profile.dev.package.byond]
opt-level = 3
