[package]
name = "ssnt"
version = "0.1.0"
authors = ["Alain Siegrist <alainsiegrist02@gmail.com>"]
edition = "2021"

[workspace]
resolver = "2"
members = ["crates/*"]

[dependencies]
byond = { path = "crates/byond" }
maps = { path = "crates/maps" }
networking = { path = "crates/networking" }
bevy = { version = "0.8", features = ["bevy_gltf"] }
bevy_egui = "0.15.0"
bevy-inspector-egui = "0.12.1"
bevy_rapier3d = { version = "0.16.0", features = ["simd-stable", "debug-render"] }
cfg-if = "1.0.0"
futures-lite = "1.4.0"
log = "0.4.8"
glam = "0.20.2"
serde = { version = "*", features = ["derive"] }
clap = { version = "3.0.13", features = ["derive"] }

[patch.crates-io]
bevy = { path = "../bevy" }

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.maps]
opt-level = 1

[profile.dev.package.byond]
opt-level = 3
