[package]
name = "networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bevy_networking_turbulence = "0.4.1"
serde = { version = "*", features = ["derive"] }
bincode = "1.3.3"
bevy_rapier3d = { version = "0.12.0" }
