[package]
name = "speech"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
ron = "0.8.1"
pink_accents = "0.0.6"
