name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install native system dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - uses: r7kamura/rust-problem-matchers@b5092889692373e09c98a0aeb380a044a651ab86
      - name: Run clippy and cargo checks
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: spacestationnt/ssnt
          tags: |
            # latest tag for main branch. by default it only sets latest for tags
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: |
            # merges (main branch) use docker hub cache
            ${{ github.event_name != 'push' && 'type=gha' || '' }}
            # main branch only uses docker hub cache because it is main branch itself while PRs use it for
            # faster initial compilation
            spacestationnt/ssnt:cache
          cache-to: |
            # merges (main branch) use docker hub cache. do not push to github
            ${{ github.event_name != 'push' && 'type=gha,mode=max' || '' }}
            # only push cache to docker hub on merge. docker dies early if this is enabled without logging in
            ${{ github.event_name == 'push' && 'type=registry,ref=spacestationnt/ssnt:cache,mode=max' || '' }}
